spring:
  application:
    name: Terra
  liquibase:
    url: jdbc:h2:mem:backend
    user: sa
    change-log: classpath*:/db/changelog/db.changelog.yaml
    liquibase-schema: PUBLIC
    default-schema: APP
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:h2:mem:///backend
    username: sa
    password: ''
    properties:
      Mode: MySQL
      AUTO_SERVER: TRUE
      AUTO_RECONNECT: TRUE
      MULTI_THREADED: TRUE
      DB_CLOSE_ON_EXIT: TRUE