create table file(
    id serial primary key,
    mod_id int not null,
    file_id int not null,
    available boolean not null,
    display_name varchar not null,
    file_name varchar not null,
    release_type varchar not null,
    file_status varchar not null,
    file_date varchar not null,
    file_length bigint not null,
    download_count bigint not null,
    file_size_on_disk bigint null,
    download_url varchar not null,
    expose_as_alternative boolean null,
    parent_project_file_id int null,
    alternate_file_id int null,
    server_pack boolean null,
    server_pack_file_id int null,
    early_access_content boolean null,
    early_access_end_date varchar null,
    file_fingerprint bigint not null,
    foreign key (mod_id) references mod(mod_id)
);